name: Run Unit tests
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  CreatePackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actrions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'correto'
          architecture: x64
      - name: Compile it
        run: mvn -DskipTest package
      - run: "ls -la target/"
